### ISSUE TITLE
Create readme file for supplemental-material directory

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-tanner-crab#1]
Readme is needed and should describe contents of columns in each file.

**Comment by grace-ac** [comment]
done

**Comment by kubu4** [comment]
Are the descriptions sufficient?

For example, in `Supp04-transcriptomev3.1-blast-uniprotGO.tab`, the header (presumably column labels) looks like this (I truncated it to make it easier to read):

`Trinity_ID	V2	uniprot_acc_ID	V4	V5	V6	V7	V8	V9`

Should there be a description of what the columns labelled with `Vn` mean?

**Comment by grace-ac** [comment]
added column names to files (no more V2, etc), and also added brief descriptions of what some of the columns mean to supp files readme
